global:
  environment: prod
  imageRegistry: "__IMAGE_REGISTRY__"
  externalServices:
    postgres:
      enabled: true
      databaseUrl: "__DB_URL__"
    redis:
      enabled: true
      redisUrl: "__REDIS_URL__"

postgres:
  enabled: false
redis:
  enabled: false
neo4j:
  enabled: false
nats:
  enabled: false
clickhouse:
  enabled: false

coreApi:
  enabled: true
  replicaCount: 2

signalApi:
  enabled: true

investigationAgent:
  enabled: false
integrationIngress:
  enabled: false
dataPlane:
  enabled: false
graphqlGateway:
  enabled: false
frontend:
  enabled: false
