global:
  environment: prod
  imageRegistry: "__IMAGE_REGISTRY__"

coreApi:
  enabled: true
signalApi:
  enabled: true
integrationIngress:
  enabled: true
graphService:
  enabled: true
investigationAgent:
  enabled: true
dataPlane:
  enabled: true
graphqlGateway:
  enabled: true
frontend:
  enabled: true
opa:
  enabled: true

postgres:
  enabled: true
redis:
  enabled: true
neo4j:
  enabled: true
nats:
  enabled: true
clickhouse:
  enabled: true
