global:
  environment: prod
  imageRegistry: "__IMAGE_REGISTRY__"
  externalServices:
    postgres:
      enabled: true
      databaseUrl: "__DB_URL__"
    redis:
      enabled: true
      redisUrl: "__REDIS_URL__"

postgres:
  enabled: false
redis:
  enabled: false
neo4j:
  enabled: false
nats:
  enabled: false
clickhouse:
  enabled: false

coreApi:
  enabled: true
  tag: "1.3.0-beta"
  replicaCount: 2
integrationIngress:
  enabled: true
  tag: "1.3.0-beta"
investigationAgent:
  enabled: true
  tag: "1.3.0-beta"
graphqlGateway:
  enabled: true
frontend:
  enabled: true

signalApi:
  enabled: true
  tag: "1.3.0-beta"
graphService:
  enabled: false
