# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import internal_comms_pb2 as internal__comms__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in internal_comms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveSignals = channel.unary_unary(
                '/tarka.internal.v1.SignalService/ResolveSignals',
                request_serializer=internal__comms__pb2.SignalResolutionRequest.SerializeToString,
                response_deserializer=internal__comms__pb2.SignalResolutionResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/tarka.internal.v1.SignalService/Ping',
                request_serializer=internal__comms__pb2.PingRequest.SerializeToString,
                response_deserializer=internal__comms__pb2.PongResponse.FromString,
                _registered_method=True)


class SignalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResolveSignals(self, request, context):
        """Batch-resolve named signals for one evaluation context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Liveness and version metadata; must remain cheap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveSignals,
                    request_deserializer=internal__comms__pb2.SignalResolutionRequest.FromString,
                    response_serializer=internal__comms__pb2.SignalResolutionResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=internal__comms__pb2.PingRequest.FromString,
                    response_serializer=internal__comms__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarka.internal.v1.SignalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarka.internal.v1.SignalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarka.internal.v1.SignalService/ResolveSignals',
            internal__comms__pb2.SignalResolutionRequest.SerializeToString,
            internal__comms__pb2.SignalResolutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarka.internal.v1.SignalService/Ping',
            internal__comms__pb2.PingRequest.SerializeToString,
            internal__comms__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
