# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal_comms.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'internal_comms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14internal_comms.proto\x12\x11tarka.internal.v1\"u\n\x17SignalResolutionRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x14\n\x0csignal_names\x18\x03 \x03(\t\x12\x1f\n\x17\x65valuation_context_json\x18\x04 \x01(\x0c\"j\n\x0eResolvedSignal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x14\n\x0cpayload_json\x18\x03 \x01(\x0c\x12\x12\n\nerror_code\x18\x04 \x01(\t\x12\x14\n\x0c\x65rror_detail\x18\x05 \x01(\t\"k\n\x18SignalResolutionResponse\x12\x32\n\x07signals\x18\x01 \x03(\x0b\x32!.tarka.internal.v1.ResolvedSignal\x12\x1b\n\x13provider_latency_ms\x18\x02 \x01(\r\"%\n\x0bPingRequest\x12\x16\n\x0e\x63\x61ller_service\x18\x01 \x01(\t\"=\n\x0cPongResponse\x12\x16\n\x0e\x63\x61llee_service\x18\x01 \x01(\t\x12\x15\n\rbuild_version\x18\x02 \x01(\t2\xc3\x01\n\rSignalService\x12i\n\x0eResolveSignals\x12*.tarka.internal.v1.SignalResolutionRequest\x1a+.tarka.internal.v1.SignalResolutionResponse\x12G\n\x04Ping\x12\x1e.tarka.internal.v1.PingRequest\x1a\x1f.tarka.internal.v1.PongResponseB\x19\n\x15\x63om.tarka.internal.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal_comms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.tarka.internal.v1P\001'
  _globals['_SIGNALRESOLUTIONREQUEST']._serialized_start=43
  _globals['_SIGNALRESOLUTIONREQUEST']._serialized_end=160
  _globals['_RESOLVEDSIGNAL']._serialized_start=162
  _globals['_RESOLVEDSIGNAL']._serialized_end=268
  _globals['_SIGNALRESOLUTIONRESPONSE']._serialized_start=270
  _globals['_SIGNALRESOLUTIONRESPONSE']._serialized_end=377
  _globals['_PINGREQUEST']._serialized_start=379
  _globals['_PINGREQUEST']._serialized_end=416
  _globals['_PONGRESPONSE']._serialized_start=418
  _globals['_PONGRESPONSE']._serialized_end=479
  _globals['_SIGNALSERVICE']._serialized_start=482
  _globals['_SIGNALSERVICE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
