"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SignalResolutionRequest(google.protobuf.message.Message):
    """---------------------------------------------------------------------------
    SignalService — unary resolution plus a cheap liveness/metadata ping.
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRACE_ID_FIELD_NUMBER: builtins.int
    TENANT_ID_FIELD_NUMBER: builtins.int
    SIGNAL_NAMES_FIELD_NUMBER: builtins.int
    EVALUATION_CONTEXT_JSON_FIELD_NUMBER: builtins.int
    trace_id: builtins.str
    """Correlates downstream logs with decision/evaluation traces (W3C trace id hex, etc.)."""
    tenant_id: builtins.str
    """Tenant / realm identifier for isolation and routing."""
    evaluation_context_json: builtins.bytes
    """Opaque JSON blob: evaluation payload slice the provider may need (bounded by policy at callers)."""
    @property
    def signal_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Logical signal identifiers (e.g. feature store keys) to resolve in one round-trip."""

    def __init__(
        self,
        *,
        trace_id: builtins.str = ...,
        tenant_id: builtins.str = ...,
        signal_names: collections.abc.Iterable[builtins.str] | None = ...,
        evaluation_context_json: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["evaluation_context_json", b"evaluation_context_json", "signal_names", b"signal_names", "tenant_id", b"tenant_id", "trace_id", b"trace_id"]) -> None: ...

global___SignalResolutionRequest = SignalResolutionRequest

@typing.final
class ResolvedSignal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    OK_FIELD_NUMBER: builtins.int
    PAYLOAD_JSON_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_DETAIL_FIELD_NUMBER: builtins.int
    name: builtins.str
    ok: builtins.bool
    payload_json: builtins.bytes
    """JSON-encoded value when ok; empty when not ok unless partial payloads are contractually allowed."""
    error_code: builtins.str
    """Stable machine-readable reason when ok is false (e.g. SIGNAL_NOT_FOUND, UPSTREAM_TIMEOUT)."""
    error_detail: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        ok: builtins.bool = ...,
        payload_json: builtins.bytes = ...,
        error_code: builtins.str = ...,
        error_detail: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_detail", b"error_detail", "name", b"name", "ok", b"ok", "payload_json", b"payload_json"]) -> None: ...

global___ResolvedSignal = ResolvedSignal

@typing.final
class SignalResolutionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIGNALS_FIELD_NUMBER: builtins.int
    PROVIDER_LATENCY_MS_FIELD_NUMBER: builtins.int
    provider_latency_ms: builtins.int
    """Optional hint: provider-side processing time excluding network to caller."""
    @property
    def signals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResolvedSignal]: ...
    def __init__(
        self,
        *,
        signals: collections.abc.Iterable[global___ResolvedSignal] | None = ...,
        provider_latency_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["provider_latency_ms", b"provider_latency_ms", "signals", b"signals"]) -> None: ...

global___SignalResolutionResponse = SignalResolutionResponse

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALLER_SERVICE_FIELD_NUMBER: builtins.int
    caller_service: builtins.str
    """Calling service name for debugging (e.g. decision-api)."""
    def __init__(
        self,
        *,
        caller_service: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["caller_service", b"caller_service"]) -> None: ...

global___PingRequest = PingRequest

@typing.final
class PongResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALLEE_SERVICE_FIELD_NUMBER: builtins.int
    BUILD_VERSION_FIELD_NUMBER: builtins.int
    callee_service: builtins.str
    build_version: builtins.str
    def __init__(
        self,
        *,
        callee_service: builtins.str = ...,
        build_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["build_version", b"build_version", "callee_service", b"callee_service"]) -> None: ...

global___PongResponse = PongResponse
