"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SignalResolutionRequest(_message.Message):
    """---------------------------------------------------------------------------
    SignalService — unary resolution plus a cheap liveness/metadata ping.
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    TRACE_ID_FIELD_NUMBER: _builtins.int
    TENANT_ID_FIELD_NUMBER: _builtins.int
    SIGNAL_NAMES_FIELD_NUMBER: _builtins.int
    EVALUATION_CONTEXT_JSON_FIELD_NUMBER: _builtins.int
    trace_id: _builtins.str
    """Correlates downstream logs with decision/evaluation traces (W3C trace id hex, etc.)."""
    tenant_id: _builtins.str
    """Tenant / realm identifier for isolation and routing."""
    evaluation_context_json: _builtins.bytes
    """Opaque JSON blob: evaluation payload slice the provider may need (bounded by policy at callers)."""
    @_builtins.property
    def signal_names(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Logical signal identifiers (e.g. feature store keys) to resolve in one round-trip."""

    def __init__(
        self,
        *,
        trace_id: _builtins.str = ...,
        tenant_id: _builtins.str = ...,
        signal_names: _abc.Iterable[_builtins.str] | None = ...,
        evaluation_context_json: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["evaluation_context_json", b"evaluation_context_json", "signal_names", b"signal_names", "tenant_id", b"tenant_id", "trace_id", b"trace_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SignalResolutionRequest: _TypeAlias = SignalResolutionRequest  # noqa: Y015

@_typing.final
class ResolvedSignal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    PAYLOAD_JSON_FIELD_NUMBER: _builtins.int
    ERROR_CODE_FIELD_NUMBER: _builtins.int
    ERROR_DETAIL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    ok: _builtins.bool
    payload_json: _builtins.bytes
    """JSON-encoded value when ok; empty when not ok unless partial payloads are contractually allowed."""
    error_code: _builtins.str
    """Stable machine-readable reason when ok is false (e.g. SIGNAL_NOT_FOUND, UPSTREAM_TIMEOUT)."""
    error_detail: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        ok: _builtins.bool = ...,
        payload_json: _builtins.bytes = ...,
        error_code: _builtins.str = ...,
        error_detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error_code", b"error_code", "error_detail", b"error_detail", "name", b"name", "ok", b"ok", "payload_json", b"payload_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolvedSignal: _TypeAlias = ResolvedSignal  # noqa: Y015

@_typing.final
class SignalResolutionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SIGNALS_FIELD_NUMBER: _builtins.int
    PROVIDER_LATENCY_MS_FIELD_NUMBER: _builtins.int
    provider_latency_ms: _builtins.int
    """Optional hint: provider-side processing time excluding network to caller."""
    @_builtins.property
    def signals(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResolvedSignal]: ...
    def __init__(
        self,
        *,
        signals: _abc.Iterable[Global___ResolvedSignal] | None = ...,
        provider_latency_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["provider_latency_ms", b"provider_latency_ms", "signals", b"signals"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SignalResolutionResponse: _TypeAlias = SignalResolutionResponse  # noqa: Y015

@_typing.final
class PingRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CALLER_SERVICE_FIELD_NUMBER: _builtins.int
    caller_service: _builtins.str
    """Calling service name for debugging (e.g. decision-api)."""
    def __init__(
        self,
        *,
        caller_service: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["caller_service", b"caller_service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PingRequest: _TypeAlias = PingRequest  # noqa: Y015

@_typing.final
class PongResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CALLEE_SERVICE_FIELD_NUMBER: _builtins.int
    BUILD_VERSION_FIELD_NUMBER: _builtins.int
    callee_service: _builtins.str
    build_version: _builtins.str
    def __init__(
        self,
        *,
        callee_service: _builtins.str = ...,
        build_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["build_version", b"build_version", "callee_service", b"callee_service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PongResponse: _TypeAlias = PongResponse  # noqa: Y015
