{{- if .Values.counterService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tarka.fullname" . }}-counter-service
spec:
  replicas: {{ .Values.counterService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tarka.fullname" . }}-counter-service
  template:
    metadata:
      labels:
        app: {{ include "tarka.fullname" . }}-counter-service
    spec:
      containers:
        - name: counter-service
          image: {{ include "tarka.image" (dict "registry" .Values.global.imageRegistry "image" .Values.counterService.image "tag" .Values.counterService.tag) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.counterService.port }}
          env:
            - name: COUNTER_SERVICE_REDIS_URL
              {{- if .Values.global.externalServices.redis.enabled }}
              value: {{ .Values.global.externalServices.redis.redisUrl | quote }}
              {{- else }}
              value: "redis://{{ include "tarka.fullname" . }}-redis:6379/0"
              {{- end }}
            {{- if .Values.global.appSecretsName }}
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.appSecretsName | quote }}
                  key: API_KEYS
                  optional: true
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarka.fullname" . }}-counter-service
spec:
  selector:
    app: {{ include "tarka.fullname" . }}-counter-service
  ports:
    - port: {{ .Values.counterService.port }}
      targetPort: {{ .Values.counterService.port }}
{{- end }}
