{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tarka.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "tarka.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "tarka.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarka.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.serviceType | default "ClusterIP" }}
  selector:
    app: {{ include "tarka.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
{{- end }}
