{{- if .Values.locationService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tarka.fullname" . }}-location-service
spec:
  replicas: {{ .Values.locationService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tarka.fullname" . }}-location-service
  template:
    metadata:
      labels:
        app: {{ include "tarka.fullname" . }}-location-service
    spec:
      containers:
        - name: location-service
          image: {{ include "tarka.image" (dict "registry" .Values.global.imageRegistry "image" .Values.locationService.image "tag" .Values.locationService.tag) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.locationService.port }}
          env:
            - name: LOCATION_SERVICE_DATA_DIR
              value: /data
            {{- if .Values.global.appSecretsName }}
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.appSecretsName | quote }}
                  key: API_KEYS
                  optional: true
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarka.fullname" . }}-location-service
spec:
  selector:
    app: {{ include "tarka.fullname" . }}-location-service
  ports:
    - port: {{ .Values.locationService.port }}
      targetPort: {{ .Values.locationService.port }}
{{- end }}
