{{- if .Values.mlScoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tarka.fullname" . }}-ml-scoring
spec:
  replicas: {{ .Values.mlScoring.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tarka.fullname" . }}-ml-scoring
  template:
    metadata:
      labels:
        app: {{ include "tarka.fullname" . }}-ml-scoring
    spec:
      containers:
        - name: ml-scoring
          image: {{ include "tarka.image" (dict "registry" .Values.global.imageRegistry "image" .Values.mlScoring.image "tag" .Values.mlScoring.tag) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mlScoring.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarka.fullname" . }}-ml-scoring
spec:
  selector:
    app: {{ include "tarka.fullname" . }}-ml-scoring
  ports:
    - port: {{ .Values.mlScoring.servicePort }}
      targetPort: {{ .Values.mlScoring.servicePort }}
{{- end }}
