"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Distinct from legacy runtime schema in ``crates/tarka-core/proto/evidence.proto`` so both
schemas can be generated in one crate without duplicate message names.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EvidenceManifest(_message.Message):
    """Canonical audit envelope for a single fraud-decision evaluation: binds identity, engine provenance,
    captured signals, per-step rule execution, the final outcome, and cryptographic binding of the
    decision trace (Merkle root + signature). Persisted for dispute resolution, regulatory inquiry,
    and deterministic replay without trusting mutable application logs alone.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SignalsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SignalValue: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___SignalValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    MANIFEST_ID_FIELD_NUMBER: _builtins.int
    OCCURRED_AT_UNIX_NS_FIELD_NUMBER: _builtins.int
    ENGINE_FIELD_NUMBER: _builtins.int
    SIGNALS_FIELD_NUMBER: _builtins.int
    TRACE_FIELD_NUMBER: _builtins.int
    VERDICT_FIELD_NUMBER: _builtins.int
    MERKLE_ROOT_FIELD_NUMBER: _builtins.int
    SIGNATURE_FIELD_NUMBER: _builtins.int
    MERKLE_PROOF_FIELD_NUMBER: _builtins.int
    manifest_id: _builtins.str
    """Stable identifier for this manifest (typically UUID string; aligns with case tools and CH manifest_id)."""
    occurred_at_unix_ns: _builtins.int
    """Wall-clock instant when the evaluation completed or when evidence was sealed: nanoseconds since Unix epoch."""
    merkle_root: _builtins.bytes
    """SHA-256 Merkle root over canonicalized trace leaves (32 bytes). Links signature to evidence content."""
    signature: _builtins.bytes
    """Digital signature over the Merkle root (e.g. Ed25519ph over prehashed root). Proves integrity non-repudiation."""
    merkle_proof: _builtins.bytes
    """rs_merkle inclusion proof over trace leaves (`MerkleProof::to_bytes`, DirectHashes order). Required
    whenever `signature` is populated (Triple-DB audit); may be zero-length when `trace` is empty.
    """
    @_builtins.property
    def engine(self) -> Global___EngineMetadata:
        """Build-time and runtime provenance of the engine that produced this manifest (who ran which code where)."""

    @_builtins.property
    def signals(self) -> _containers.MessageMap[_builtins.str, Global___SignalValue]:
        """Normalized feature/signal inputs and enrichments keyed by stable signal id at evaluation time."""

    @_builtins.property
    def trace(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExecutionStep]:
        """Ordered rule-engine steps; proves how the verdict was reached for auditor and replay tooling."""

    @_builtins.property
    def verdict(self) -> Global___Verdict:
        """Final orchestrated outcome: decision label, risk score, routing tags, and measured latency."""

    def __init__(
        self,
        *,
        manifest_id: _builtins.str = ...,
        occurred_at_unix_ns: _builtins.int = ...,
        engine: Global___EngineMetadata | None = ...,
        signals: _abc.Mapping[_builtins.str, Global___SignalValue] | None = ...,
        trace: _abc.Iterable[Global___ExecutionStep] | None = ...,
        verdict: Global___Verdict | None = ...,
        merkle_root: _builtins.bytes = ...,
        signature: _builtins.bytes = ...,
        merkle_proof: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_merkle_proof", b"_merkle_proof", "engine", b"engine", "merkle_proof", b"merkle_proof", "verdict", b"verdict"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_merkle_proof", b"_merkle_proof", "engine", b"engine", "manifest_id", b"manifest_id", "merkle_proof", b"merkle_proof", "merkle_root", b"merkle_root", "occurred_at_unix_ns", b"occurred_at_unix_ns", "signals", b"signals", "signature", b"signature", "trace", b"trace", "verdict", b"verdict"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__merkle_proof: _TypeAlias = _typing.Literal["merkle_proof"]  # noqa: Y015
    _WhichOneofArgType__merkle_proof: _TypeAlias = _typing.Literal["_merkle_proof", b"_merkle_proof"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__merkle_proof) -> _WhichOneofReturnType__merkle_proof | None: ...

Global___EvidenceManifest: _TypeAlias = EvidenceManifest  # noqa: Y015

@_typing.final
class EngineMetadata(_message.Message):
    """Identifies the software artifact and deployment context that executed the policy graph."""

    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    GIT_HASH_FIELD_NUMBER: _builtins.int
    ENVIRONMENT_FIELD_NUMBER: _builtins.int
    ENGINE_INSTANCE_ID_FIELD_NUMBER: _builtins.int
    version: _builtins.str
    """Semantic engine release (semver or internal label embedded at build)."""
    git_hash: _builtins.str
    """Exact VCS revision used to build the engine binary (full git SHA preferred)."""
    environment: _builtins.str
    """Deployment slice: prod, staging, sandbox, or region-specific label for blast-radius analysis."""
    engine_instance_id: _builtins.str
    """Stable id for the running engine replica/pod (correlates with infra logs when investigating drift)."""
    def __init__(
        self,
        *,
        version: _builtins.str = ...,
        git_hash: _builtins.str = ...,
        environment: _builtins.str = ...,
        engine_instance_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["engine_instance_id", b"engine_instance_id", "environment", b"environment", "git_hash", b"git_hash", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EngineMetadata: _TypeAlias = EngineMetadata  # noqa: Y015

@_typing.final
class SignalValue(_message.Message):
    """Typed scalar payload for a named signal; preserves numeric vs string vs opaque blob for faithful replay."""

    DESCRIPTOR: _descriptor.Descriptor

    STR_VAL_FIELD_NUMBER: _builtins.int
    NUM_VAL_FIELD_NUMBER: _builtins.int
    BOOL_VAL_FIELD_NUMBER: _builtins.int
    RAW_BYTES_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    str_val: _builtins.str
    """UTF-8 string bucket (free-form categories, short codes, hashed ids where policy allows)."""
    num_val: _builtins.float
    """Floating scalar (scores, amounts, model probabilities)."""
    bool_val: _builtins.bool
    """Boolean flags from lists, velocity thresholds, or binary model outputs."""
    raw_bytes: _builtins.bytes
    """Opaque binary (serialized embeddings, protobuf submessages, or redacted blobs stored verbatim)."""
    source: _builtins.str
    """Upstream label for audit: which connector, model version, or resolver produced this value."""
    def __init__(
        self,
        *,
        str_val: _builtins.str = ...,
        num_val: _builtins.float = ...,
        bool_val: _builtins.bool = ...,
        raw_bytes: _builtins.bytes = ...,
        source: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_val", b"bool_val", "num_val", b"num_val", "raw_bytes", b"raw_bytes", "str_val", b"str_val", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_val", b"bool_val", "num_val", b"num_val", "raw_bytes", b"raw_bytes", "source", b"source", "str_val", b"str_val", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["str_val", "num_val", "bool_val", "raw_bytes"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___SignalValue: _TypeAlias = SignalValue  # noqa: Y015

@_typing.final
class ExecutionStep(_message.Message):
    """One rule-evaluation step within the ordered trace; captures subtree evaluation for dispute debugging."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StateSnapshotEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SEQUENCE_FIELD_NUMBER: _builtins.int
    RULE_ID_FIELD_NUMBER: _builtins.int
    OPERATOR_FIELD_NUMBER: _builtins.int
    OPERANDS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    STATE_SNAPSHOT_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    """Monotonic position in the evaluation DAG traversal (reconstruct order even if logs interleave)."""
    rule_id: _builtins.str
    """Stable id of the rule or leaf node evaluated at this step (maps to policy repo definitions)."""
    operator: _builtins.str
    """Logical combinator or opcode for this node (e.g. AND, OR, GT, MATCH — engine-defined vocabulary)."""
    result: _builtins.bool
    """Truth value of this step after applying the operator to operands under the current snapshot."""
    @_builtins.property
    def operands(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Operand references or literal handles fed to the operator (paths, constant ids, child rule ids)."""

    @_builtins.property
    def state_snapshot(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Compact key/value snapshot of resolver state after the step (bounded strings for audit storage)."""

    def __init__(
        self,
        *,
        sequence: _builtins.int = ...,
        rule_id: _builtins.str = ...,
        operator: _builtins.str = ...,
        operands: _abc.Iterable[_builtins.str] | None = ...,
        result: _builtins.bool = ...,
        state_snapshot: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operands", b"operands", "operator", b"operator", "result", b"result", "rule_id", b"rule_id", "sequence", b"sequence", "state_snapshot", b"state_snapshot"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecutionStep: _TypeAlias = ExecutionStep  # noqa: Y015

@_typing.final
class Verdict(_message.Message):
    """Final decision surface exposed to orchestration and downstream systems."""

    DESCRIPTOR: _descriptor.Descriptor

    ACTION_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    LATENCY_NS_FIELD_NUMBER: _builtins.int
    action: _builtins.str
    """Primary routing decision (e.g. allow, review, deny — product vocabulary; contract-level enum may wrap this)."""
    score: _builtins.float
    """Aggregated risk or confidence score used for thresholding and analytics."""
    latency_ns: _builtins.int
    """End-to-end evaluation latency in nanoseconds (SLI/SLO and latency forensics)."""
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Tags emitted for explainability, policy routing, or consortium exchange (dedup not guaranteed)."""

    def __init__(
        self,
        *,
        action: _builtins.str = ...,
        score: _builtins.float = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        latency_ns: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "latency_ns", b"latency_ns", "score", b"score", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Verdict: _TypeAlias = Verdict  # noqa: Y015
