# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarka/evidence/wire/v1/evidence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tarka/evidence/wire/v1/evidence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%tarka/evidence/wire/v1/evidence.proto\x12\x16tarka.evidence.wire.v1\"\xd5\x03\n\x10\x45videnceManifest\x12\x13\n\x0bmanifest_id\x18\x01 \x01(\t\x12\x1b\n\x13occurred_at_unix_ns\x18\x02 \x01(\x04\x12\x36\n\x06\x65ngine\x18\x03 \x01(\x0b\x32&.tarka.evidence.wire.v1.EngineMetadata\x12\x46\n\x07signals\x18\x04 \x03(\x0b\x32\x35.tarka.evidence.wire.v1.EvidenceManifest.SignalsEntry\x12\x34\n\x05trace\x18\x05 \x03(\x0b\x32%.tarka.evidence.wire.v1.ExecutionStep\x12\x30\n\x07verdict\x18\x06 \x01(\x0b\x32\x1f.tarka.evidence.wire.v1.Verdict\x12\x13\n\x0bmerkle_root\x18\x07 \x01(\x0c\x12\x11\n\tsignature\x18\x08 \x01(\x0c\x12\x19\n\x0cmerkle_proof\x18\t \x01(\x0cH\x00\x88\x01\x01\x1aS\n\x0cSignalsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.tarka.evidence.wire.v1.SignalValue:\x02\x38\x01\x42\x0f\n\r_merkle_proof\"d\n\x0e\x45ngineMetadata\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08git_hash\x18\x02 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x03 \x01(\t\x12\x1a\n\x12\x65ngine_instance_id\x18\x04 \x01(\t\"u\n\x0bSignalValue\x12\x11\n\x07str_val\x18\x01 \x01(\tH\x00\x12\x11\n\x07num_val\x18\x02 \x01(\x01H\x00\x12\x12\n\x08\x62ool_val\x18\x03 \x01(\x08H\x00\x12\x13\n\traw_bytes\x18\x04 \x01(\x0cH\x00\x12\x0e\n\x06source\x18\x05 \x01(\tB\x07\n\x05value\"\xee\x01\n\rExecutionStep\x12\x10\n\x08sequence\x18\x01 \x01(\r\x12\x0f\n\x07rule_id\x18\x02 \x01(\t\x12\x10\n\x08operator\x18\x03 \x01(\t\x12\x10\n\x08operands\x18\x04 \x03(\t\x12\x0e\n\x06result\x18\x05 \x01(\x08\x12P\n\x0estate_snapshot\x18\x06 \x03(\x0b\x32\x38.tarka.evidence.wire.v1.ExecutionStep.StateSnapshotEntry\x1a\x34\n\x12StateSnapshotEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"J\n\x07Verdict\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x12\n\nlatency_ns\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarka.evidence.wire.v1.evidence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVIDENCEMANIFEST_SIGNALSENTRY']._loaded_options = None
  _globals['_EVIDENCEMANIFEST_SIGNALSENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTIONSTEP_STATESNAPSHOTENTRY']._loaded_options = None
  _globals['_EXECUTIONSTEP_STATESNAPSHOTENTRY']._serialized_options = b'8\001'
  _globals['_EVIDENCEMANIFEST']._serialized_start=66
  _globals['_EVIDENCEMANIFEST']._serialized_end=535
  _globals['_EVIDENCEMANIFEST_SIGNALSENTRY']._serialized_start=435
  _globals['_EVIDENCEMANIFEST_SIGNALSENTRY']._serialized_end=518
  _globals['_ENGINEMETADATA']._serialized_start=537
  _globals['_ENGINEMETADATA']._serialized_end=637
  _globals['_SIGNALVALUE']._serialized_start=639
  _globals['_SIGNALVALUE']._serialized_end=756
  _globals['_EXECUTIONSTEP']._serialized_start=759
  _globals['_EXECUTIONSTEP']._serialized_end=997
  _globals['_EXECUTIONSTEP_STATESNAPSHOTENTRY']._serialized_start=945
  _globals['_EXECUTIONSTEP_STATESNAPSHOTENTRY']._serialized_end=997
  _globals['_VERDICT']._serialized_start=999
  _globals['_VERDICT']._serialized_end=1073
# @@protoc_insertion_point(module_scope)
