"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Distinct from legacy runtime schema in `crates/tarka-core/proto/evidence.proto` so both
schemas can be generated in one crate without duplicate message names.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EvidenceManifest(google.protobuf.message.Message):
    """Canonical audit envelope for a single fraud-decision evaluation: binds identity, engine provenance,
    captured signals, per-step rule execution, the final outcome, and cryptographic binding of the
    decision trace (Merkle root + signature). Persisted for dispute resolution, regulatory inquiry,
    and deterministic replay without trusting mutable application logs alone.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class SignalsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___SignalValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___SignalValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    MANIFEST_ID_FIELD_NUMBER: builtins.int
    OCCURRED_AT_UNIX_NS_FIELD_NUMBER: builtins.int
    ENGINE_FIELD_NUMBER: builtins.int
    SIGNALS_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    VERDICT_FIELD_NUMBER: builtins.int
    MERKLE_ROOT_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    MERKLE_PROOF_FIELD_NUMBER: builtins.int
    manifest_id: builtins.str
    """Stable identifier for this manifest (typically UUID string; aligns with case tools and CH manifest_id)."""
    occurred_at_unix_ns: builtins.int
    """Wall-clock instant when the evaluation completed or when evidence was sealed: nanoseconds since Unix epoch."""
    merkle_root: builtins.bytes
    """SHA-256 Merkle root over canonicalized trace leaves (32 bytes). Links signature to evidence content."""
    signature: builtins.bytes
    """Digital signature over the Merkle root (e.g. Ed25519ph over prehashed root). Proves integrity non-repudiation."""
    merkle_proof: builtins.bytes
    """rs_merkle inclusion proof over trace leaves (`MerkleProof::to_bytes`, DirectHashes order). Required
    whenever `signature` is populated (Triple-DB audit); may be zero-length when `trace` is empty.
    """
    @property
    def engine(self) -> global___EngineMetadata:
        """Build-time and runtime provenance of the engine that produced this manifest (who ran which code where)."""

    @property
    def signals(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___SignalValue]:
        """Normalized feature/signal inputs and enrichments keyed by stable signal id at evaluation time."""

    @property
    def trace(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ExecutionStep]:
        """Ordered rule-engine steps; proves how the verdict was reached for auditor and replay tooling."""

    @property
    def verdict(self) -> global___Verdict:
        """Final orchestrated outcome: decision label, risk score, routing tags, and measured latency."""

    def __init__(
        self,
        *,
        manifest_id: builtins.str = ...,
        occurred_at_unix_ns: builtins.int = ...,
        engine: global___EngineMetadata | None = ...,
        signals: collections.abc.Mapping[builtins.str, global___SignalValue] | None = ...,
        trace: collections.abc.Iterable[global___ExecutionStep] | None = ...,
        verdict: global___Verdict | None = ...,
        merkle_root: builtins.bytes = ...,
        signature: builtins.bytes = ...,
        merkle_proof: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_merkle_proof", b"_merkle_proof", "engine", b"engine", "merkle_proof", b"merkle_proof", "verdict", b"verdict"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_merkle_proof", b"_merkle_proof", "engine", b"engine", "manifest_id", b"manifest_id", "merkle_proof", b"merkle_proof", "merkle_root", b"merkle_root", "occurred_at_unix_ns", b"occurred_at_unix_ns", "signals", b"signals", "signature", b"signature", "trace", b"trace", "verdict", b"verdict"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_merkle_proof", b"_merkle_proof"]) -> typing.Literal["merkle_proof"] | None: ...

global___EvidenceManifest = EvidenceManifest

@typing.final
class EngineMetadata(google.protobuf.message.Message):
    """Identifies the software artifact and deployment context that executed the policy graph."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    GIT_HASH_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    ENGINE_INSTANCE_ID_FIELD_NUMBER: builtins.int
    version: builtins.str
    """Semantic engine release (semver or internal label embedded at build)."""
    git_hash: builtins.str
    """Exact VCS revision used to build the engine binary (full git SHA preferred)."""
    environment: builtins.str
    """Deployment slice: prod, staging, sandbox, or region-specific label for blast-radius analysis."""
    engine_instance_id: builtins.str
    """Stable id for the running engine replica/pod (correlates with infra logs when investigating drift)."""
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        git_hash: builtins.str = ...,
        environment: builtins.str = ...,
        engine_instance_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["engine_instance_id", b"engine_instance_id", "environment", b"environment", "git_hash", b"git_hash", "version", b"version"]) -> None: ...

global___EngineMetadata = EngineMetadata

@typing.final
class SignalValue(google.protobuf.message.Message):
    """Typed scalar payload for a named signal; preserves numeric vs string vs opaque blob for faithful replay."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STR_VAL_FIELD_NUMBER: builtins.int
    NUM_VAL_FIELD_NUMBER: builtins.int
    BOOL_VAL_FIELD_NUMBER: builtins.int
    RAW_BYTES_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    str_val: builtins.str
    """UTF-8 string bucket (free-form categories, short codes, hashed ids where policy allows)."""
    num_val: builtins.float
    """Floating scalar (scores, amounts, model probabilities)."""
    bool_val: builtins.bool
    """Boolean flags from lists, velocity thresholds, or binary model outputs."""
    raw_bytes: builtins.bytes
    """Opaque binary (serialized embeddings, protobuf submessages, or redacted blobs stored verbatim)."""
    source: builtins.str
    """Upstream label for audit: which connector, model version, or resolver produced this value."""
    def __init__(
        self,
        *,
        str_val: builtins.str = ...,
        num_val: builtins.float = ...,
        bool_val: builtins.bool = ...,
        raw_bytes: builtins.bytes = ...,
        source: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bool_val", b"bool_val", "num_val", b"num_val", "raw_bytes", b"raw_bytes", "str_val", b"str_val", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bool_val", b"bool_val", "num_val", b"num_val", "raw_bytes", b"raw_bytes", "source", b"source", "str_val", b"str_val", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["str_val", "num_val", "bool_val", "raw_bytes"] | None: ...

global___SignalValue = SignalValue

@typing.final
class ExecutionStep(google.protobuf.message.Message):
    """One rule-evaluation step within the ordered trace; captures subtree evaluation for dispute debugging."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class StateSnapshotEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SEQUENCE_FIELD_NUMBER: builtins.int
    RULE_ID_FIELD_NUMBER: builtins.int
    OPERATOR_FIELD_NUMBER: builtins.int
    OPERANDS_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    STATE_SNAPSHOT_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """Monotonic position in the evaluation DAG traversal (reconstruct order even if logs interleave)."""
    rule_id: builtins.str
    """Stable id of the rule or leaf node evaluated at this step (maps to policy repo definitions)."""
    operator: builtins.str
    """Logical combinator or opcode for this node (e.g. AND, OR, GT, MATCH — engine-defined vocabulary)."""
    result: builtins.bool
    """Truth value of this step after applying the operator to operands under the current snapshot."""
    @property
    def operands(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Operand references or literal handles fed to the operator (paths, constant ids, child rule ids)."""

    @property
    def state_snapshot(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Compact key/value snapshot of resolver state after the step (bounded strings for audit storage)."""

    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
        rule_id: builtins.str = ...,
        operator: builtins.str = ...,
        operands: collections.abc.Iterable[builtins.str] | None = ...,
        result: builtins.bool = ...,
        state_snapshot: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operands", b"operands", "operator", b"operator", "result", b"result", "rule_id", b"rule_id", "sequence", b"sequence", "state_snapshot", b"state_snapshot"]) -> None: ...

global___ExecutionStep = ExecutionStep

@typing.final
class Verdict(google.protobuf.message.Message):
    """Final decision surface exposed to orchestration and downstream systems."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTION_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    LATENCY_NS_FIELD_NUMBER: builtins.int
    action: builtins.str
    """Primary routing decision (e.g. allow, review, deny — product vocabulary; contract-level enum may wrap this)."""
    score: builtins.float
    """Aggregated risk or confidence score used for thresholding and analytics."""
    latency_ns: builtins.int
    """End-to-end evaluation latency in nanoseconds (SLI/SLO and latency forensics)."""
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Tags emitted for explainability, policy routing, or consortium exchange (dedup not guaranteed)."""

    def __init__(
        self,
        *,
        action: builtins.str = ...,
        score: builtins.float = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        latency_ns: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action", b"action", "latency_ns", b"latency_ns", "score", b"score", "tags", b"tags"]) -> None: ...

global___Verdict = Verdict
