#!/usr/bin/env python3
"""Generate Helm values from cloud deployment presets."""

from __future__ import annotations

import argparse
from pathlib import Path


PRESET_DIR = Path("deploy/helm/fraud-stack/presets")
PLACEHOLDER_MAP = {
    "__IMAGE_REGISTRY__": "image_registry",
    "__DB_URL__": "db_url",
    "__REDIS_URL__": "redis_url",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate cloud-specific Helm values from a preset.")
    parser.add_argument("--preset", required=True, choices=sorted(p.stem for p in PRESET_DIR.glob("*.yaml")), help="Preset name without .yaml")
    parser.add_argument("--image-registry", dest="image_registry", default="", help="Container registry prefix, e.g. <acct>.dkr.ecr.<region>.amazonaws.com/tarka")
    parser.add_argument("--db-url", dest="db_url", default="", help="Managed Postgres URL for presets that require it")
    parser.add_argument("--redis-url", dest="redis_url", default="", help="Managed Redis URL for presets that require it")
    parser.add_argument("--namespace", default="", help="Optional namespace comment for generated file headers")
    parser.add_argument("--output", required=True, help="Output values file path")
    return parser.parse_args()


def ensure_placeholders_are_resolved(raw: str) -> list[str]:
    unresolved: list[str] = []
    for placeholder in PLACEHOLDER_MAP:
        if placeholder in raw:
            unresolved.append(placeholder)
    return unresolved


def main() -> int:
    args = parse_args()

    preset_path = PRESET_DIR / f"{args.preset}.yaml"
    if not preset_path.exists():
        raise SystemExit(f"Preset not found: {preset_path}")

    rendered = preset_path.read_text(encoding="utf-8")
    for placeholder, arg_name in PLACEHOLDER_MAP.items():
        value = getattr(args, arg_name, "")
        if value:
            rendered = rendered.replace(placeholder, value)

    unresolved = ensure_placeholders_are_resolved(rendered)
    if unresolved:
        missing_args = sorted({PLACEHOLDER_MAP[item] for item in unresolved})
        raise SystemExit(
            "Missing required arguments for preset placeholders: "
            + ", ".join(f"--{arg.replace('_', '-')}" for arg in missing_args)
        )

    header = [
        "# Generated by scripts/deploy/generate_cloud_values.py",
        f"# Preset: {args.preset}",
    ]
    if args.namespace:
        header.append(f"# Namespace: {args.namespace}")

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(header) + "\n\n" + rendered + "\n", encoding="utf-8")

    print(f"Generated values file: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
