{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tarka.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tarka.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "tarka.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "tarka.image" (dict "registry" .Values.global.imageRegistry "image" .Values.frontend.image "tag" .Values.frontend.tag) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarka.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.serviceType | default "ClusterIP" }}
  selector:
    app: {{ include "tarka.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
{{- end }}
