{{- if .Values.graphqlGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tarka.fullname" . }}-graphql-gateway
spec:
  replicas: {{ .Values.graphqlGateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tarka.fullname" . }}-graphql-gateway
  template:
    metadata:
      labels:
        app: {{ include "tarka.fullname" . }}-graphql-gateway
    spec:
      containers:
        - name: graphql-gateway
          image: {{ include "tarka.image" (dict "registry" .Values.global.imageRegistry "image" .Values.graphqlGateway.image "tag" .Values.graphqlGateway.tag) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.graphqlGateway.port }}
          env:
            - name: DECISION_API_URL
              value: {{ .Values.graphqlGateway.decisionApiUrl | default (printf "http://%s-core-api:%v/decisions" (include "tarka.fullname" .) (.Values.coreApi.servicePort | int)) | quote }}
            - name: CASE_API_URL
              value: {{ .Values.graphqlGateway.caseApiUrl | default (printf "http://%s-core-api:%v/cases" (include "tarka.fullname" .) (.Values.coreApi.servicePort | int)) | quote }}
            - name: GRAPH_SERVICE_URL
              {{- if or .Values.graphService.enabled .Values.graphqlGateway.graphServiceUrl }}
              value: {{ .Values.graphqlGateway.graphServiceUrl | default (printf "http://%s-graph-service:8001" (include "tarka.fullname" .)) | quote }}
              {{- else }}
              value: ""
              {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.graphqlGateway.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarka.fullname" . }}-graphql-gateway
spec:
  selector:
    app: {{ include "tarka.fullname" . }}-graphql-gateway
  ports:
    - port: {{ .Values.graphqlGateway.port }}
      targetPort: {{ .Values.graphqlGateway.port }}
{{- end }}
