"""Stack outputs for FastAPI services (Triple-DB: Postgres, Redis, ClickHouse).

Builds URLs and a multi-line ``.env`` fragment matching :class:`pydantic_settings.BaseSettings`
field names used by ``services/decision-api`` (``DATABASE_URL``, ``REDIS_URL``, ``CLICKHOUSE_*``).

Write locally after ``pulumi up``::

    pulumi stack output tripleDbDotenv --show-secrets > .env.triple-db

Do not commit ``--show-secrets`` output. Prefer injecting from Pulumi ESC / CI secret stores in production.
"""

from __future__ import annotations

from urllib.parse import quote

import pulumi


def _database_url(
    host: str,
    port: int,
    user: str,
    password: str,
    database: str,
    sslmode: str,
) -> str:
    u = quote(user, safe="")
    p = quote(password, safe="")
    db = quote(database, safe="")
    base = f"postgresql+asyncpg://{u}:{p}@{host}:{port}/{db}"
    sm = (sslmode or "prefer").strip().lower()
    if sm in ("require", "verify-ca", "verify-full"):
        return f"{base}?ssl=require"
    if sm in ("disable", "allow", "prefer"):
        return base
    return f"{base}?sslmode={quote(sm, safe='')}"


def _redis_url(host: str, port: int, db: int, password: str) -> str:
    if password.strip():
        pw = quote(password, safe="")
        return f"redis://:{pw}@{host}:{port}/{db}"
    return f"redis://{host}:{port}/{db}"


def _env_line(key: str, value: str) -> str:
    """Emit KEY=value for dotenv; always double-quote values so URLs and passwords parse reliably."""
    esc = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'{key}="{esc}"'


def _dotenv_block(
    *,
    database_url: str,
    redis_url: str,
    clickhouse_host: str,
    clickhouse_http_port: int,
    clickhouse_native_port: int,
    clickhouse_user: str,
    clickhouse_password: str,
    clickhouse_database: str,
) -> str:
    lines = [
        "# Generated by Triple-DB Pulumi (deploy/fastapi_env.py) — Postgres, Redis, ClickHouse",
        _env_line("DATABASE_URL", database_url),
        _env_line("REDIS_URL", redis_url),
        _env_line("CLICKHOUSE_HOST", clickhouse_host),
        _env_line("CLICKHOUSE_PORT", str(clickhouse_http_port)),
        _env_line("CLICKHOUSE_USER", clickhouse_user),
        _env_line("CLICKHOUSE_PASSWORD", clickhouse_password),
        _env_line("CLICKHOUSE_DATABASE", clickhouse_database),
        "# Native protocol port (clickhouse-connect uses HTTP by default; tools may use 9000)",
        _env_line("CLICKHOUSE_NATIVE_PORT", str(clickhouse_native_port)),
    ]
    return "\n".join(lines) + "\n"


def export_fastapi_triple_db_outputs(*, cfg: pulumi.Config) -> None:
    """Export connection strings and a combined ``.env`` fragment as stack outputs."""
    pg_pw = cfg.require_secret("postgresPassword")
    ch_pw = cfg.get_secret("clickhousePassword")
    if ch_pw is None:
        ch_pw = pulumi.Output.from_input("")
    redis_pw = cfg.get_secret("redisPassword")
    if redis_pw is None:
        redis_pw = pulumi.Output.from_input("")

    combined = pulumi.Output.all(
        cfg.require("postgresHost"),
        cfg.require_int("postgresPort"),
        cfg.require("postgresUser"),
        pg_pw,
        cfg.require("postgresDatabase"),
        cfg.get("postgresSslmode") or "prefer",
        cfg.require("redisHost"),
        cfg.require_int("redisPort"),
        cfg.require_int("redisDb"),
        redis_pw,
        cfg.require("clickhouseHost"),
        cfg.require_int("clickhouseHttpPort"),
        cfg.require_int("clickhouseNativePort"),
        cfg.get("clickhouseAdminUser") or "default",
        ch_pw,
        cfg.require("clickhouseDatabase"),
    ).apply(
        lambda p: (
            _database_url(
                str(p[0]),
                int(p[1]),
                str(p[2]),
                str(p[3]),
                str(p[4]),
                str(p[5]),
            ),
            _redis_url(str(p[6]), int(p[7]), int(p[8]), str(p[9])),
            str(p[10]),
            int(p[11]),
            int(p[12]),
            str(p[13]),
            str(p[14]),
            str(p[15]),
        )
    )

    db_url = combined.apply(lambda t: t[0])
    redis_url = combined.apply(lambda t: t[1])
    dotenv = combined.apply(
        lambda t: _dotenv_block(
            database_url=t[0],
            redis_url=t[1],
            clickhouse_host=t[2],
            clickhouse_http_port=t[3],
            clickhouse_native_port=t[4],
            clickhouse_user=t[5],
            clickhouse_password=t[6],
            clickhouse_database=t[7],
        )
    )

    pulumi.export("fastapiDatabaseUrl", pulumi.Output.secret(db_url))
    pulumi.export("fastapiRedisUrl", pulumi.Output.secret(redis_url))
    pulumi.export("tripleDbDotenv", pulumi.Output.secret(dotenv))
