global:
  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/wafv2-acl-arn: "__AWS_WAFV2_ACL_ARN__"
    frontendHost: "__FRONTEND_HOST__"
    graphqlHost: "__GRAPHQL_HOST__"

coreApi:
  edgeSecurity:
    enabled: true
    wafActionHeader: x-amzn-waf-action
    botScoreHeader: x-amzn-bot-score
    botScoreBlockThreshold: 25
    botScoreReviewThreshold: 50
