global:
  environment: prod
  imageRegistry: "__IMAGE_REGISTRY__"

decisionApi:
  enabled: true
caseApi:
  enabled: true
integrationIngress:
  enabled: true
featureService:
  enabled: true
mlScoring:
  enabled: true
graphService:
  enabled: true
investigationAgent:
  enabled: true
eventIngest:
  enabled: true
analyticsSink:
  enabled: true
graphqlGateway:
  enabled: true
frontend:
  enabled: true
counterService:
  enabled: true
locationService:
  enabled: true
opa:
  enabled: true

postgres:
  enabled: true
redis:
  enabled: true
neo4j:
  enabled: true
nats:
  enabled: true
clickhouse:
  enabled: true
